"use client";
import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, LockKeyhole, UserRound } from "lucide-react";
import { getInitials } from "@/lib/domain/profile";

export default function ProfilePage() {
  const [profile, setProfile] = useState<{ nome?: string | null; email: string } | null>(null);
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/auth/profile").then((r) => r.ok ? r.json() : null).then(setProfile); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); setMessage(""); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const payload: Record<string, string> = { nome: String(values.nome) }; if (values.newPassword) payload.newPassword = String(values.newPassword); const response = await fetch("/api/auth/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) setError(data.error ?? "Não foi possível salvar."); else { setProfile(data); setMessage("Perfil atualizado com sucesso."); (event.currentTarget.elements.namedItem("newPassword") as HTMLInputElement).value = ""; } setSaving(false); }
  return <main className="min-h-screen bg-slate-50 p-6 text-slate-950 dark:bg-slate-950 dark:text-slate-100 lg:p-10"><div className="mx-auto max-w-2xl"><a href="/" className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-blue-600"><ArrowLeft size={16} /> Voltar</a><div className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-4"><div className="grid size-14 place-items-center rounded-full bg-blue-100 text-lg font-bold text-blue-700">{getInitials(profile?.nome, profile?.email)}</div><div><p className="text-sm text-slate-400">Meu perfil</p><h1 className="text-2xl font-semibold">Dados de acesso</h1></div></div><form key={profile?.email} onSubmit={submit} className="mt-8 space-y-5"><label className="block text-sm font-medium">Nome<input name="nome" required minLength={2} defaultValue={profile?.nome ?? ""} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500 dark:border-slate-700 dark:bg-slate-800" /></label><label className="block text-sm font-medium">E-mail<input disabled value={profile?.email ?? ""} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-slate-500 dark:border-slate-700 dark:bg-slate-800" /></label><label className="block text-sm font-medium"><span className="flex items-center gap-2"><LockKeyhole size={15} /> Nova senha</span><input name="newPassword" type="password" minLength={8} placeholder="Deixe em branco para manter" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500 dark:border-slate-700 dark:bg-slate-800" /></label>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-600">{error}</p>}{message && <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}<button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60"><UserRound size={16} />{saving ? "Salvando..." : "Salvar perfil"}</button></form></div></div></main>;
}
