import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { z } from "zod";
const schema = z.object({ nome: z.string().trim().min(2), email: z.string().email(), password: z.string().min(8), role: z.enum(["Owner", "User"]) });
async function actor() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return { supabase, user: null, profile: null }; const { data: profile } = await supabase.from("users").select("workspace_id, role").eq("id", user.id).single(); return { supabase, user, profile }; }
export async function GET() { const { supabase, user, profile } = await actor(); if (!user) return NextResponse.json({ error: "Não autenticado" }, { status: 401 }); if (!profile) return NextResponse.json({ error: "Perfil não configurado" }, { status: 403 }); const { data, error } = await supabase.from("users").select("id,nome,email,role,ativo").eq("workspace_id", profile.workspace_id).order("created_at"); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json(data); }
export async function POST(request: Request) { const { user, profile } = await actor(); if (!user) return NextResponse.json({ error: "Não autenticado" }, { status: 401 }); if (!profile || !["Admin Master", "Owner"].includes(profile.role)) return NextResponse.json({ error: "Sem permissão" }, { status: 403 }); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 }); const admin = createAdminClient(); const created = await admin.auth.admin.createUser({ email: parsed.data.email, password: parsed.data.password, email_confirm: true }); if (created.error || !created.data.user) return NextResponse.json({ error: created.error?.message ?? "Falha ao criar usuário" }, { status: 500 }); const { error } = await admin.from("users").insert({ id: created.data.user.id, workspace_id: profile.workspace_id, nome: parsed.data.nome, email: parsed.data.email, role: parsed.data.role, ativo: true }); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json({ id: created.data.user.id, email: parsed.data.email }, { status: 201 }); }
export async function PATCH(request: Request) { const { supabase, user, profile } = await actor(); if (!user) return NextResponse.json({ error: "Não autenticado" }, { status: 401 }); if (!profile || !["Admin Master", "Owner"].includes(profile.role)) return NextResponse.json({ error: "Sem permissão" }, { status: 403 }); const body = await request.json().catch(() => ({})); if (typeof body.id !== "string" || typeof body.ativo !== "boolean") return NextResponse.json({ error: "Dados inválidos" }, { status: 400 }); const { data, error } = await supabase.from("users").update({ ativo: body.ativo }).eq("id", body.id).eq("workspace_id", profile.workspace_id).select("id,nome,email,role,ativo").single(); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json(data); }
